// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqoEQ7enyuX8JtxCIvY_BxEabyHlBsw5k',
    appId: '1:46562349973:web:50f3d8520ac49b17ee9c9c',
    messagingSenderId: '46562349973',
    projectId: 'thesis-d7a11',
    authDomain: 'thesis-d7a11.firebaseapp.com',
    storageBucket: 'thesis-d7a11.firebasestorage.app',
    measurementId: 'G-J2PL3ZHRNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaMPNrRMbdeQ71oZdZIcekK21ygjRsXFU',
    appId: '1:46562349973:android:5d5e809f7d0c1e27ee9c9c',
    messagingSenderId: '46562349973',
    projectId: 'thesis-d7a11',
    storageBucket: 'thesis-d7a11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwdTnCBEFTwoZQ-RWNpGXRHJ2prHGWfMQ',
    appId: '1:46562349973:ios:0c2510fdc27fa4afee9c9c',
    messagingSenderId: '46562349973',
    projectId: 'thesis-d7a11',
    storageBucket: 'thesis-d7a11.firebasestorage.app',
    iosBundleId: 'com.example.appTry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwdTnCBEFTwoZQ-RWNpGXRHJ2prHGWfMQ',
    appId: '1:46562349973:ios:0c2510fdc27fa4afee9c9c',
    messagingSenderId: '46562349973',
    projectId: 'thesis-d7a11',
    storageBucket: 'thesis-d7a11.firebasestorage.app',
    iosBundleId: 'com.example.appTry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqoEQ7enyuX8JtxCIvY_BxEabyHlBsw5k',
    appId: '1:46562349973:web:4f437599523bea20ee9c9c',
    messagingSenderId: '46562349973',
    projectId: 'thesis-d7a11',
    authDomain: 'thesis-d7a11.firebaseapp.com',
    storageBucket: 'thesis-d7a11.firebasestorage.app',
    measurementId: 'G-0FBEFXXNJ7',
  );
}
